M48
; DRILL file {KiCad (6.0.7)} date Fri Feb 24 22:01:17 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-24T22:01:17+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1122
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X1.5496Y-2.0819
X1.5496Y-5.5819
T2
X2.1945Y-2.9157
T0
M30
